name: ai_os
description: "Provider-agnostic architecture for a native Windows AI application."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  audioplayers: ^6.8.1
  camera: ^0.12.0+2
  camera_desktop: ^1.2.1
  crypto: ^3.0.7
  face_detection_tflite: ^6.8.0
  ffi: ^2.2.0
  flutter:
    sdk: flutter
  path_provider: ^2.1.6
  webview_flutter_windows: 1.1.1
  window_manager: ^0.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  shaders:
    - lib/ui/world/ai_core/shaders/living_ai_core.frag


